spring:
  cloud:
    nacos:
      username: nacos
      password: nacos
      server-addr: 39.98.82.109:8848
      discovery:
        namespace: 98f83d2d-9740-4b0d-b158-dae97e5d0a4a
        group: DEFAULT_GROUP
      config:
        server-addr: 39.98.82.109:8848
        namespace: 98f83d2d-9740-4b0d-b158-dae97e5d0a4a
        group: DEFAULT_GROUP
        file-extension: yaml
  config:
    import:
      - optional:nacos:${spring.application.name}
